### ISSUE TITLE
How to delete item manually

### ISSUE THREAD

**Issue by joielechong** [fluttercandies/flutter_draggable_container#2]
Thanks for this amazing library!

I've some problem with library, I need to remove an item without using the default delete icon. I want to use a button inside the item to delete itself. Of course I can just rebuild the widget by refreshing the item list but it seems like a hack.

Can you give an example for that?

**Comment by gzlock** [comment]
The DraggableContainerState has a deleteItem(T item) method, it will use
null to instead of the target item.
Same as using the insteadOf(int index, null) method.

**Comment by gzlock** [comment]
Hey dude, I update 0.1.8+2.
Add a list of methods on README.md
