### ISSUE TITLE
Using Container for GridView

### ISSUE THREAD

**Issue by ManojMM026** [fluttercandies/flutter_draggable_container#3]
Hey, Great lib, one of the smoothest list I've came across on pub.dev.

Can you tell me How do I use this create draggable grid view?

**Comment by gzlock** [comment]
It defaults to the grid style

**Comment by ManojMM026** [comment]
Not as good as default grid view though. I need exact grid view like implementation.  Eg. I can specify column count here, I am stuck with adding ListView and specifying slotSize.
It will be really helpful if you can add gird view implementation to lib or in example.

**Comment by gzlock** [comment]
So your requirement is the DraggableContainer can accept any parameters like the GirdView?

**Comment by ManojMM026** [comment]
Yes, I don't think any other lib provide experience as smooth as this one. But need gridview implementation.

**Comment by ManojMM026** [comment]
any updates on this?

**Comment by gzlock** [comment]
> any updates on this?

Very sorry, I busy with other projects in the last half year
Recently there is no way to update the project

**Comment by gzlock** [comment]
Hi buddy, now this package is null safety and support SliverGridDelegate 🎉 .
It keep smooth.
![img](https://github.com/gzlock/images/raw/master/flutter_draggable_container/1.gif)
