### ISSUE TITLE
Possibility to change edit mode externally

### ISSUE THREAD

**Issue by ShiroYacha** [fluttercandies/flutter_draggable_container#4]
Hi,

Would it be possible to have a controlled edit mode where we can change it externally? An example use case is to have this in a in-line editor where there is no "back" button or the "confirm" button will not leave the page. 

Maybe we can trigger this in the controller?

Best regards,
Min

**Comment by gzlock** [comment]
Very sorry about I haven't paid attention to this project for a while.
You can set the onDraggableModeChanged function to the container, when the edit mode changed will trigger this function.
If you want to exit the edit mode, for example: you can use the GestureDetector wrap the container and exit the edit mode in the onTap function.

**Comment by gzlock** [comment]
Hi dude, it support `(GlobalKey<DraggableContainerState> state).currentState.editMode = false;` to exit the edit mode now.
And when tap outside the widget to exit the edit mode(`tapOutsideExitEditMode` default is `true`).
